### PR TITLE
Feature/j1939 devices

### PR DESCRIPTION
**Pull request by simonkerscher**
J1939 (one of the two major CAN standards) defines lots of messages in its digital annex  (search for J1939DA_201907.xls in our GDrive), which are used in compliant devices, e.g. IMUs, engine control units, GPS devices, joysticks, ...

This repo aims to slowly move this functionality in one common place. Restructuring other nodes (e.g. lord_microstrain_imu, pump_controller_can, rototilt_can, cat323_lowlevel_controller::Imu) would come in a second step.

I have the following problems with this approach, where I would appreciate input:

- The digital annex linked above is copyrighted, so I am unsure how much of the implementation I can opensource. A similar package (https://github.com/nmfta-repo/pretty_j1939) goes the approach of requiring purchase of the standard by users of their library, and later want to include a basic database compiled from public information (e.g. datasheets). We could go this route for most devices, I think. This would just limit how extensively we can comment our code.
- What units should we return? Where do we do the conversion? The standard defines some messages in non-SI units such as rpm, degrees, % of engine stroke) It's clear to me, that data needs to be in SI-units before entering our other software packages, however it could be beneficial to make the msg-definition a purely mechanical adaptation of the standard. To facilitate this, I only converted units in the device, but not yet in the message.

### CODE REVIEW

**Comment by djud** [comment]
If you think it would be helpful to have the entire j1939 standard already implemented I would create a second repo that we keep private. However I don't know how much that really helps. We can just add additional devices once we need them. This means we would only have a few devices inplemented from other documentation and not all 200 which lets ud fly under the radar maybe.

An other guy put this:
Most of the informations about SAE J1939 are taken from the papers and the book of [Copperhill technologies](http://copperhilltech.com/a-brief-introduction-to-the-sae-j1939-protocol/) and from my many years of experience in J1939 of course :-)

**Comment by djud** [comment]
Regarding the conversion: If we use a standard, we should stick to the standard. Thus I would do it as you proposed. Msg is as the standard suggests, then add a conversion in the device implementation.

**Comment by simonkerscher** [comment]
> If you think it would be helpful to have the entire j1939 standard already implemented I would create a second repo that we keep private. However I don't know how much that really helps. We can just add additional devices once we need them. This means we would only have a few devices inplemented from other documentation and not all 200 which lets ud fly under the radar maybe.
> 
> An other guy put this: Most of the informations about SAE J1939 are taken from the papers and the book of [Copperhill technologies](http://copperhilltech.com/a-brief-introduction-to-the-sae-j1939-protocol/) and from my many years of experience in J1939 of course :-)

Yes, I was not planning to implement everything immediately, but add to it as needed.

**Comment by jelavice** [comment]
Agree with the conversion. Stick to the standard and do the conversion in device drivers.

**Comment by jelavice** [comment]
If the open sourcing implementation is a problem would just precompiling j1939 related code and releasing it as a library be an option?

**Pull request merged**
